In [2]:
import numpy as np
import pandas as pd

### Creating numpy arrays

In [29]:
array1 = np.array([1,2,3,4])
print(array1)

random_array = np.random.rand(3)
print(random_array)

zero_matrix = np.zeros((2,3))
print(zero_matrix)

ones_array = np.ones(3)
print(ones_array)

full_array = np.full((2,3),'A')
print(full_array)

range_array = np.arange(1,5)
print(range_array)

random_matrix = np.random.randn(2,3)
print(random_matrix)

eye_matrix = np.eye(3,3)
print(eye_matrix)

identity_matrix = np.identity(5)
print(identity_matrix) 

[1 2 3 4]
[0.72707662 0.09343519 0.42494065]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[['A' 'A' 'A']
 ['A' 'A' 'A']]
[1 2 3 4]
[[ 0.88886464  0.99162051 -1.30579286]
 [ 1.92765828 -0.38376945 -0.36400685]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### finding shape and type

In [32]:
print(random_matrix.shape) #returns a tuple
print(random_matrix.dtype)
print(random_matrix.ndim)

(2, 3)
float64
2


In [3]:
my_numpy_array 

array([0.09959711, 0.31364725, 0.22146903])

In [6]:
my_series = pd.Series(my_numpy_array)

In [7]:
my_series

0    0.099597
1    0.313647
2    0.221469
dtype: float64

In [8]:
my_series.index = ["one","two","three"]

In [9]:
my_series

one      0.099597
two      0.313647
three    0.221469
dtype: float64

In [10]:
array_2d = np.random.rand(3,2)

In [11]:
my_df = pd.DataFrame(array_2d)

In [12]:
my_df 

0         1
0  0.134884  0.828487
1  0.338675  0.674116
2  0.557512  0.006718

In [14]:
my_df.columns = ["One","Two"]

In [15]:
my_df 

One       Two
0  0.134884  0.828487
1  0.338675  0.674116
2  0.557512  0.006718